#ifndef GUARD_VILLAGES_TILESET_H
#define GUARD_VILLAGES_TILESET_H

#define TILESET_ROTATION_A 0
#define TILESET_ROTATION_B 1
#define TILESET_ROTATION_C 2
#define TILESET_ROTATION_D 3
#define TILESET_ROTATION_COUNT 4

#define TILESET_TILE_COUNT 23

#define TILESET_TILE_SIZE_IN_BINARY_SHIFT 5

#endif
